package company.Main.MainView.Login.Ostalo;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;


import company.Main.Support.Izvodi.StringToSplit;
import javafx.event.ActionEvent;

public class LeftOstaloController implements Initializable {
	@FXML
	private Button btnIzvodiKM;
	@FXML
	private Button btnPlate;
	@FXML
	private Button btnSihtarica;
	@FXML
	private Button btnPutNalog;
	@FXML
	private Button btnToGlavniMeni;
	@FXML
	private Button exit;

	// Event Listener on Button[#btnIzvodiKM].onAction
	@FXML
	public void goToIzvodKM(ActionEvent event) throws IOException {
		clearPreviousData ();
		company.Main.Main.changeCenterMain("MainView/Login/Ostalo/Izvodi/TableIzvodKM.fxml");
	}
	
	// Event Listener on Button[#btnPlate].onAction
	@FXML
	public void goToPlate(ActionEvent event) {
		clearPreviousData ();
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSihtarica].onAction
	@FXML
	public void goToSihtarica(ActionEvent event) {
		clearPreviousData ();
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPutNalog].onAction
		@FXML
		public void goToPutniNalog(ActionEvent event) throws IOException {
			clearPreviousData ();
			company.Main.Main.changeCenterMain("MainView/Login/Ostalo/PutniNalog/PutniNalog.fxml");
		}
	// Event Listener on Button[#btnToGlavniMeni].onAction
	@FXML
	public void goToGlavniMeni(ActionEvent event) throws IOException {
		clearPreviousData ();
		company.Main.Main.changeCenterMain("MainView/CenterView.fxml");
		company.Main.Main.changeLeftMain("MainView/LeftMain.fxml");
	}
	// Event Listener on Button[#exit].onAction
	@FXML
	public void close(ActionEvent event) throws SQLException {
		company.Main.DBConnection.DBConnection.dbDisconnect();
		System.exit(0);
	}
	
	public void clearPreviousData (){		
		StringToSplit.clearAllArrayLists();
	}
	
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
