package company.Main.MainView.Login.Sifarnik.Korisnici;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class LeftSifarnikKorisniciController implements Initializable {
	@FXML
	private Button btnNewKorisnik;
	@FXML
	private Button btnEditKorisnik;
	@FXML
	private Button btnDeleteKorisnik;
	@FXML
	private Button btnShowKorisnici;
	@FXML
	private Button btnToSifarnik;
	@FXML
	private Button exit;

	// Event Listener on Button[#btnNewKorisnik].onAction
	@FXML
	public void goToInsertKorisnik(ActionEvent event) throws IOException {
		company.Main.Main.changeCenterMain("MainView/Login/Sifarnik/Korisnici/SifarnikKorisnici.fxml");
	}
	// Event Listener on Button[#btnEditKorisnik].onAction
	@FXML
	public void goToEditKorisnik(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDeleteKorisnik].onAction
	@FXML
	public void goToDeleteKorisnik(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnShowKorisnici].onAction
	@FXML
	public void goShowKorisnici(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnToSifarnik].onAction
	@FXML
	public void goToSifarnikMeni(ActionEvent event) throws IOException {
		company.Main.Main.changeCenterMain("MainView/CenterView.fxml");
		company.Main.Main.changeLeftMain("MainView/Login/Sifarnik/LeftSifarnik.fxml");
	}
	// Event Listener on Button[#exit].onAction
	@FXML
	public void close(ActionEvent event) throws SQLException {
		company.Main.DBConnection.DBConnection.dbDisconnect();
		System.exit(0);
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	
}
