package company.Main.MainView;

import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Tooltip;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;

public class TopIconController implements Initializable {
	@FXML
	private VBox vbMenuRight;
	@FXML
	private ImageView backupIcon;
	@FXML
	private ImageView restoreIcon;
	@FXML
	private ImageView infoIcon;
	@FXML
	private ImageView minIcon;
	@FXML
	private ImageView closeIcon;
	@FXML
	private HBox hbIcon;
	@FXML
	private HBox hb;
	@FXML
	private Pane paneBackup;
	@FXML
	private Pane paneRestore;
	@FXML
	private Pane paneInfo;
	@FXML
	private Pane paneMin;
	@FXML
	private Pane paneClose;
	
	
	// Event Listener on ImageView[#backupIcon].onMouseClicked
	@FXML
	public void backupDataBase(MouseEvent event) throws IOException, InterruptedException {
	
		company.Main.Support.MySQLDump.MySQLDump.exportData(".sql");
	}
	
	// Event Listener on ImageView[#restoreIcon].onMouseClicked
	@FXML
	public void restoreData(MouseEvent event) throws IOException, InterruptedException {
		company.Main.Support.MySQLDump.MySQLDump.importData();
	}
	
	// Event Listener on ImageView[#infoIcon].onMouseClicked
	@FXML
	public void aboutProgram(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#minIcon].onMouseClicked
	@FXML
	public void minimizeStage(MouseEvent event) {
		company.Main.Main.stage.setIconified(true);
	}
	// Event Listener on ImageView[#closeIcon].onMouseClicked
	@FXML
	public void closeStage(MouseEvent event) throws SQLException {
		company.Main.DBConnection.DBConnection.dbDisconnect();
		System.exit(0);
	}

	public void setTooltip (String text, ImageView iv){
		Tooltip t= new Tooltip(text);
		Tooltip.install(iv, t);
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		
		setTooltip("BACKUP DATA", backupIcon);
		setTooltip("RESTORE DATA", restoreIcon);
		setTooltip("ABOUT PROGRAM", infoIcon);
		setTooltip("MINIMIZE WINDOW", minIcon);
		setTooltip("CLOSE WINDOW", closeIcon);
	}
	
}
